version: "3.7"
services:
  postgres_source:
    image: postgres:latest
    container_name: postgres_source
    restart: always
    ports:
      - 127.0.0.1:45433:5432
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
  postgres_sink:
    image: postgres:latest
    container_name: postgres_sink
    restart: always
    ports:
      - 127.0.0.1:45439:5432
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
